"""
Metrics collection for research benchmarking.
Captures detailed timing breakdowns for TokenWire vs Baseline comparison.

This module provides comprehensive instrumentation for measuring:
- Tokenization time
- Time to first token generated
- Time to first token sent
- Inter-token intervals (for jitter analysis)
- Total generation time
- Bandwidth metrics

Usage:
    from app.services.metrics import StreamMetrics, log_metrics

    metrics = StreamMetrics()
    metrics.start_prompt()
    metrics.start_tokenization()
    # ... tokenize ...
    metrics.end_tokenization()
    metrics.record_first_token()
    # ... for each token ...
    metrics.record_token(bytes_sent)
    metrics.end_stream()

    log_metrics("TOKENWIRE", metrics)
"""

import time
import json
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict, Any
import logging

logger = logging.getLogger(__name__)


@dataclass
class StreamMetrics:
    """
    Detailed metrics for a single stream session.

    Captures all timing information needed for research analysis including
    latency breakdown, jitter analysis, and bandwidth measurements.

    Attributes:
        prompt_received_at: Timestamp when prompt was received (ms)
        tokenization_start: Timestamp when tokenization started (ms)
        tokenization_end: Timestamp when tokenization completed (ms)
        first_token_generated_at: Timestamp when first token was generated by model (ms)
        first_token_sent_at: Timestamp when first token was sent to client (ms)
        stream_end_at: Timestamp when stream completed (ms)
        total_tokens: Total number of tokens generated
        total_bytes_sent: Total bytes transmitted
        token_timestamps: List of timestamps for each token (ms)
        token_sizes: List of byte sizes for each token transmission
        protocol: Protocol identifier (tokenwire/baseline)
        prompt_length: Length of input prompt in characters
        model_name: Name of the model used
    """

    # Timing breakdown (all in milliseconds from perf_counter)
    prompt_received_at: float = 0.0
    tokenization_start: float = 0.0
    tokenization_end: float = 0.0
    first_token_generated_at: float = 0.0
    first_token_sent_at: float = 0.0
    stream_end_at: float = 0.0

    # Token metrics
    total_tokens: int = 0
    total_bytes_sent: int = 0

    # Per-token timing (for jitter analysis)
    token_timestamps: List[float] = field(default_factory=list)
    token_sizes: List[int] = field(default_factory=list)

    # Context information
    protocol: str = ""
    prompt_length: int = 0
    model_name: str = ""

    # Internal state
    _first_token_recorded: bool = field(default=False, repr=False)
    _first_send_recorded: bool = field(default=False, repr=False)

    def start_prompt(self) -> None:
        """Mark the timestamp when prompt was received."""
        self.prompt_received_at = time.perf_counter() * 1000

    def start_tokenization(self) -> None:
        """Mark the start of tokenization."""
        self.tokenization_start = time.perf_counter() * 1000

    def end_tokenization(self) -> None:
        """Mark the end of tokenization."""
        self.tokenization_end = time.perf_counter() * 1000

    def record_first_token_generated(self) -> None:
        """
        Mark when the first token was generated by the model.
        Should be called once when the model produces its first token.
        """
        if not self._first_token_recorded:
            self.first_token_generated_at = time.perf_counter() * 1000
            self._first_token_recorded = True

    def record_first_token_sent(self) -> None:
        """
        Mark when the first token was sent to the client.
        Should be called once after the first send operation.
        """
        if not self._first_send_recorded:
            self.first_token_sent_at = time.perf_counter() * 1000
            self._first_send_recorded = True

    # Backwards compatibility aliases
    def record_first_token(self) -> None:
        """Alias for record_first_token_generated (backwards compatibility)."""
        self.record_first_token_generated()

    def record_first_send(self) -> None:
        """Alias for record_first_token_sent (backwards compatibility)."""
        self.record_first_token_sent()

    def record_token(self, bytes_sent: int = 0) -> None:
        """
        Record a token transmission.

        Args:
            bytes_sent: Number of bytes sent for this token/batch.
        """
        timestamp = time.perf_counter() * 1000
        self.token_timestamps.append(timestamp)
        self.token_sizes.append(bytes_sent)
        self.total_tokens += 1
        self.total_bytes_sent += bytes_sent

    def record_token_batch(self, token_count: int, bytes_sent: int) -> None:
        """
        Record a batch of tokens transmitted together.

        Args:
            token_count: Number of tokens in the batch.
            bytes_sent: Total bytes sent for the batch.
        """
        timestamp = time.perf_counter() * 1000
        # Record one timestamp per batch, but track all tokens
        self.token_timestamps.append(timestamp)
        self.token_sizes.append(bytes_sent)
        self.total_tokens += token_count
        self.total_bytes_sent += bytes_sent

    def end_stream(self) -> None:
        """Mark the end of the stream."""
        self.stream_end_at = time.perf_counter() * 1000

    # ─── Computed Properties ───────────────────────────────────────────────────

    @property
    def tokenization_time_ms(self) -> float:
        """Time spent tokenizing the prompt (ms)."""
        if self.tokenization_end > 0 and self.tokenization_start > 0:
            return self.tokenization_end - self.tokenization_start
        return 0.0

    @property
    def time_to_first_token_generated_ms(self) -> float:
        """Time from prompt received to first token generated (ms)."""
        if self.first_token_generated_at > 0 and self.prompt_received_at > 0:
            return self.first_token_generated_at - self.prompt_received_at
        return 0.0

    @property
    def time_to_first_token_sent_ms(self) -> float:
        """Time from prompt received to first token sent to client (ms)."""
        if self.first_token_sent_at > 0 and self.prompt_received_at > 0:
            return self.first_token_sent_at - self.prompt_received_at
        return 0.0

    @property
    def total_generation_time_ms(self) -> float:
        """Total time from prompt to stream end (ms)."""
        if self.stream_end_at > 0 and self.prompt_received_at > 0:
            return self.stream_end_at - self.prompt_received_at
        return 0.0

    @property
    def inference_time_ms(self) -> float:
        """Time spent in model inference (generation excluding tokenization) (ms)."""
        if self.stream_end_at > 0 and self.tokenization_end > 0:
            return self.stream_end_at - self.tokenization_end
        return 0.0

    @property
    def network_send_time_ms(self) -> float:
        """Estimated time spent sending tokens (total - TTFT) (ms)."""
        if self.stream_end_at > 0 and self.first_token_sent_at > 0:
            return self.stream_end_at - self.first_token_sent_at
        return 0.0

    @property
    def tokens_per_second(self) -> float:
        """Throughput in tokens per second."""
        if self.total_tokens > 0 and self.network_send_time_ms > 0:
            return self.total_tokens / (self.network_send_time_ms / 1000)
        return 0.0

    @property
    def bytes_per_token(self) -> float:
        """Average bytes transmitted per token."""
        if self.total_tokens > 0:
            return self.total_bytes_sent / self.total_tokens
        return 0.0

    # ─── Jitter Analysis ───────────────────────────────────────────────────────

    def get_inter_token_intervals(self) -> List[float]:
        """
        Calculate intervals between consecutive token transmissions.

        Returns:
            List of intervals in milliseconds.
        """
        if len(self.token_timestamps) < 2:
            return []

        return [
            self.token_timestamps[i] - self.token_timestamps[i - 1]
            for i in range(1, len(self.token_timestamps))
        ]

    def calculate_jitter(self) -> float:
        """
        Calculate jitter (standard deviation of inter-token intervals).

        Jitter measures the variability in token delivery timing.
        Lower jitter indicates more consistent streaming.

        Returns:
            Standard deviation of inter-token intervals (ms).
        """
        intervals = self.get_inter_token_intervals()

        if not intervals:
            return 0.0

        mean = sum(intervals) / len(intervals)
        variance = sum((x - mean) ** 2 for x in intervals) / len(intervals)
        return variance ** 0.5

    def calculate_jitter_stats(self) -> Dict[str, float]:
        """
        Calculate comprehensive jitter statistics.

        Returns:
            Dictionary with jitter metrics:
            - mean_interval_ms: Average time between tokens
            - std_interval_ms: Standard deviation (jitter)
            - min_interval_ms: Minimum interval
            - max_interval_ms: Maximum interval
            - p50_interval_ms: Median interval
            - p95_interval_ms: 95th percentile interval
            - p99_interval_ms: 99th percentile interval
        """
        intervals = self.get_inter_token_intervals()

        if not intervals:
            return {
                'mean_interval_ms': 0.0,
                'std_interval_ms': 0.0,
                'min_interval_ms': 0.0,
                'max_interval_ms': 0.0,
                'p50_interval_ms': 0.0,
                'p95_interval_ms': 0.0,
                'p99_interval_ms': 0.0,
            }

        sorted_intervals = sorted(intervals)
        n = len(sorted_intervals)

        def percentile(data: List[float], p: float) -> float:
            k = (len(data) - 1) * (p / 100)
            f = int(k)
            c = min(f + 1, len(data) - 1)
            return data[f] + (k - f) * (data[c] - data[f])

        mean = sum(intervals) / n
        variance = sum((x - mean) ** 2 for x in intervals) / n

        return {
            'mean_interval_ms': mean,
            'std_interval_ms': variance ** 0.5,
            'min_interval_ms': min(intervals),
            'max_interval_ms': max(intervals),
            'p50_interval_ms': percentile(sorted_intervals, 50),
            'p95_interval_ms': percentile(sorted_intervals, 95),
            'p99_interval_ms': percentile(sorted_intervals, 99),
        }

    # ─── Export Methods ────────────────────────────────────────────────────────

    def to_dict(self) -> Dict[str, Any]:
        """
        Export metrics as a dictionary for logging/analysis.

        Returns:
            Dictionary with all computed metrics.
        """
        jitter_stats = self.calculate_jitter_stats()

        return {
            # Timing breakdown
            'tokenization_time_ms': round(self.tokenization_time_ms, 3),
            'time_to_first_token_generated_ms': round(self.time_to_first_token_generated_ms, 3),
            'time_to_first_token_sent_ms': round(self.time_to_first_token_sent_ms, 3),
            'total_generation_time_ms': round(self.total_generation_time_ms, 3),
            'inference_time_ms': round(self.inference_time_ms, 3),
            'network_send_time_ms': round(self.network_send_time_ms, 3),

            # Backwards compatibility aliases
            'time_to_first_token_ms': round(self.time_to_first_token_generated_ms, 3),
            'time_to_first_send_ms': round(self.time_to_first_token_sent_ms, 3),
            'total_stream_time_ms': round(self.total_generation_time_ms, 3),

            # Token metrics
            'total_tokens': self.total_tokens,
            'total_bytes': self.total_bytes_sent,
            'tokens_per_second': round(self.tokens_per_second, 3),
            'bytes_per_token': round(self.bytes_per_token, 3),

            # Jitter metrics
            'inter_token_jitter_ms': round(jitter_stats['std_interval_ms'], 3),
            'jitter': jitter_stats,

            # Context
            'protocol': self.protocol,
            'prompt_length': self.prompt_length,
            'model_name': self.model_name,
        }

    def to_json(self) -> str:
        """
        Export metrics as a JSON string.

        Returns:
            JSON string representation of metrics.
        """
        return json.dumps(self.to_dict(), indent=2)

    def to_flat_dict(self) -> Dict[str, Any]:
        """
        Export metrics as a flat dictionary (for CSV export).

        Returns:
            Flat dictionary with all metrics as top-level keys.
        """
        base = self.to_dict()
        jitter = base.pop('jitter', {})

        # Flatten jitter stats
        for key, value in jitter.items():
            base[f'jitter_{key}'] = round(value, 3) if isinstance(value, float) else value

        return base

    # ─── Legacy Compatibility ──────────────────────────────────────────────────

    def _calculate_jitter(self) -> float:
        """Legacy method for backwards compatibility."""
        return self.calculate_jitter()


def log_metrics(protocol: str, metrics: StreamMetrics) -> None:
    """
    Log metrics in structured format for analysis.

    Args:
        protocol: Protocol identifier (e.g., "TOKENWIRE", "BASELINE").
        metrics: StreamMetrics instance to log.
    """
    data = metrics.to_dict()
    logger.info(f"[METRICS:{protocol}] {json.dumps(data)}")


def create_metrics(protocol: str = "", prompt_length: int = 0, model_name: str = "") -> StreamMetrics:
    """
    Factory function to create a new StreamMetrics instance with context.

    Args:
        protocol: Protocol identifier.
        prompt_length: Length of the input prompt.
        model_name: Name of the model being used.

    Returns:
        Configured StreamMetrics instance.
    """
    metrics = StreamMetrics()
    metrics.protocol = protocol
    metrics.prompt_length = prompt_length
    metrics.model_name = model_name
    return metrics


class MetricsCollector:
    """
    Collector for aggregating metrics across multiple streams.

    Useful for batch benchmarking and statistical analysis.
    """

    def __init__(self):
        self.metrics_list: List[StreamMetrics] = []

    def add(self, metrics: StreamMetrics) -> None:
        """Add a metrics instance to the collection."""
        self.metrics_list.append(metrics)

    def clear(self) -> None:
        """Clear all collected metrics."""
        self.metrics_list.clear()

    def get_summary(self) -> Dict[str, Any]:
        """
        Calculate summary statistics across all collected metrics.

        Returns:
            Dictionary with aggregated statistics.
        """
        if not self.metrics_list:
            return {'count': 0}

        def stats(values: List[float]) -> Dict[str, float]:
            if not values:
                return {'mean': 0, 'std': 0, 'min': 0, 'max': 0}
            n = len(values)
            mean = sum(values) / n
            variance = sum((x - mean) ** 2 for x in values) / n if n > 1 else 0
            return {
                'mean': round(mean, 3),
                'std': round(variance ** 0.5, 3),
                'min': round(min(values), 3),
                'max': round(max(values), 3),
            }

        ttft_values = [m.time_to_first_token_sent_ms for m in self.metrics_list if m.time_to_first_token_sent_ms > 0]
        tps_values = [m.tokens_per_second for m in self.metrics_list if m.tokens_per_second > 0]
        bpt_values = [m.bytes_per_token for m in self.metrics_list if m.bytes_per_token > 0]
        jitter_values = [m.calculate_jitter() for m in self.metrics_list]

        return {
            'count': len(self.metrics_list),
            'total_tokens': sum(m.total_tokens for m in self.metrics_list),
            'total_bytes': sum(m.total_bytes_sent for m in self.metrics_list),
            'ttft_ms': stats(ttft_values),
            'tokens_per_second': stats(tps_values),
            'bytes_per_token': stats(bpt_values),
            'jitter_ms': stats(jitter_values),
        }

    def to_list(self) -> List[Dict[str, Any]]:
        """Export all metrics as a list of dictionaries."""
        return [m.to_dict() for m in self.metrics_list]

    def to_json(self) -> str:
        """Export all metrics as JSON."""
        return json.dumps({
            'summary': self.get_summary(),
            'metrics': self.to_list()
        }, indent=2)
